# Generated by Django 2.1.7 on 2019-03-05 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_auto_20190305_0207'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entrys',
            new_name='Entry',
        ),
    ]
