# Generated by Django 2.1.7 on 2019-03-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_auto_20190305_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(default='entrez topic', max_length=200),
        ),
    ]
