# Generated by Django 2.1.7 on 2019-07-07 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_auto_20190707_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='owner',
            new_name='ownere',
        ),
    ]
